name: my_gojek_driver
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
  animated_splash_screen: ^1.3.0
  flutter_easyloading: ^3.0.5
  flutter: 
    sdk: flutter
  google_maps_flutter: ^2.1.9
  progress_indicators: ^1.0.0
  geocoding: ^2.0.4
  geolocator: ^9.0.1
  firebase_database: ^9.0.19
  firebase_core: ^1.19.2
  flutter_polyline_points: ^1.0.0
  flutter_phone_direct_caller: ^2.1.0
  flutter_secure_storage: ^5.0.2
  dio: ^4.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  pinput: ^2.2.12
  flutter_credit_card: ^3.0.3
  async: ^2.8.2
dev_dependencies: 
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/vehicleIcon/