name: my_gojek_driver
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
  animated_splash_screen: ^1.3.0
  flutter_easyloading: ^3.0.5
  flutter: 
    sdk: flutter
  google_maps_flutter: ^2.1.9
  progress_indicators: ^1.0.0
  geocoding: ^2.0.4
  geolocator: ^9.0.1
  firebase_database: ^9.0.19
  firebase_core: ^1.19.2
  flutter_polyline_points: ^1.0.0
  flutter_phone_direct_caller: ^2.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/vehicleIcon/